namespace WepApi.Utils;

public class Iso4217
{
    private static Iso4217Definition _notFoundDefinition = new("NotFound", -1);
    private static List<Iso4217Definition> _definitionCollection = new()
    {
            new("AED", 784),
            new("AFN", 971),
            new("ALL", 8),
            new("AMD", 51),
            new("ANG", 532),
            new("AOA", 973),
            new("ARS", 32),
            new("AUD", 36),
            new("AWG", 533),
            new("AZN", 944),
            new("BAM", 977),
            new("BBD", 52),
            new("BDT", 50),
            new("BGN", 975),
            new("BHD", 48),
            new("BIF", 108),
            new("BMD", 60),
            new("BND", 96),
            new("BOB", 68),
            new("BOV", 984),
            new("BRL", 986),
            new("BSD", 44),
            new("BTN", 64),
            new("BWP", 72),
            new("BYR", 974),
            new("BZD", 84),
            new("CAD", 124),
            new("CDF", 976),
            new("CHE", 947),
            new("CHF", 756),
            new("CHW", 948),
            new("CLF", 990),
            new("CLP", 152),
            new("CNY", 156),
            new("COP", 170),
            new("COU", 970),
            new("CRC", 188),
            new("CUC", 931),
            new("CUP", 192),
            new("CVE", 132),
            new("CZK", 203),
            new("DJF", 262),
            new("DKK", 208),
            new("DOP", 214),
            new("DZD", 12),
            new("EGP", 818),
            new("ERN", 232),
            new("ETB", 230),
            new("EUR", 978),
            new("FJD", 242),
            new("FKP", 238),
            new("GBP", 826),
            new("GEL", 981),
            new("GHS", 936),
            new("GIP", 292),
            new("GMD", 270),
            new("GNF", 324),
            new("GTQ", 320),
            new("GYD", 328),
            new("HKD", 344),
            new("HNL", 340),
            new("HRK", 191),
            new("HTG", 332),
            new("HUF", 348),
            new("IDR", 360),
            new("ILS", 376),
            new("INR", 356),
            new("IQD", 368),
            new("IRR", 364),
            new("ISK", 352),
            new("JMD", 388),
            new("JOD", 400),
            new("JPY", 392),
            new("KES", 404),
            new("KGS", 417),
            new("KHR", 116),
            new("KMF", 174),
            new("KPW", 408),
            new("KRW", 410),
            new("KWD", 414),
            new("KYD", 136),
            new("KZT", 398),
            new("LAK", 418),
            new("LBP", 422),
            new("LKR", 144),
            new("LRD", 430),
            new("LSL", 426),
            new("LTL", 440),
            new("LVL", 428),
            new("LYD", 434),
            new("MAD", 504),
            new("MDL", 498),
            new("MGA", 969),
            new("MKD", 807),
            new("MMK", 104),
            new("MNT", 496),
            new("MOP", 446),
            new("MRO", 478),
            new("MUR", 480),
            new("MVR", 462),
            new("MWK", 454),
            new("MXN", 484),
            new("MXV", 979),
            new("MYR", 458),
            new("MZN", 943),
            new("NAD", 516),
            new("NGN", 566),
            new("NIO", 558),
            new("NOK", 578),
            new("NPR", 524),
            new("NZD", 554),
            new("OMR", 512),
            new("PAB", 590),
            new("PEN", 604),
            new("PGK", 598),
            new("PHP", 608),
            new("PKR", 586),
            new("PLN", 985),
            new("PYG", 600),
            new("QAR", 634),
            new("RON", 946),
            new("RSD", 941),
            new("RUB", 643),
            new("RWF", 646),
            new("SAR", 682),
            new("SBD", 90),
            new("SCR", 690),
            new("SDG", 938),
            new("SEK", 752),
            new("SGD", 702),
            new("SHP", 654),
            new("SLL", 694),
            new("SOS", 706),
            new("SRD", 968),
            new("SSP", 728),
            new("STD", 678),
            new("SYP", 760),
            new("SZL", 748),
            new("THB", 764),
            new("TJS", 972),
            new("TMT", 934),
            new("TND", 788),
            new("TOP", 776),
            new("TRY", 949),
            new("TTD", 780),
            new("TWD", 901),
            new("TZS", 834),
            new("UAH", 980),
            new("UGX", 800),
            new("USD", 840),
            new("USN", 997),
            new("USS", 998),
            new("UYI", 940),
            new("UYU", 858),
            new("UZS", 860),
            new("VEF", 937),
            new("VND", 704),
            new("VUV", 548),
            new("WST", 882),
            new("XAF", 950),
            new("XCD", 951),
            new("XOF", 952),
            new("XPF", 953),
            new("YER", 886),
            new("ZAR", 710),
            new("ZMW", 967)
        };

    public static Iso4217Definition LookupByCode(string code) => (_definitionCollection.SingleOrDefault(d => d.Code == code.ToUpper())) ?? _notFoundDefinition;

    public static Iso4217Definition LookupByNumber(int number) => (_definitionCollection.SingleOrDefault(d => d.Number == number)) ?? _notFoundDefinition;

    public class Iso4217Definition(string code, int number)
    {
        public string Code
        {
            get { return code; }
        }
        public int Number
        {
            get { return number; }
        }
    }

}
